In [1]:
import nympy as np

ModuleNotFoundError: No module named 'nympy'

In [2]:
import numpy as np

In [5]:
array_2d = np.arange(50).reshape(5,10)

In [7]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [8]:
array_2d[array_2d < 6]

array([0, 1, 2, 3, 4, 5])

In [12]:
array_sliced = array_2d[1:3,3:5]

In [13]:
array_sliced

array([[13, 14],
       [23, 24]])

In [14]:
array_sliced[array_sliced < 20]

array([13, 14])