In [2]:
from sklearn.datasets import load_iris
import pandas as pd
iris_dataset = load_iris()

In [2]:
print("Keys \n{}".format(iris_dataset.keys()))

Keys 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [2]:
A=[1,2,3]

for a in A:

  print(2*a)

2
4
6


In [3]:
x=0
while(x<2):
  print(x)
  x=x+1

0
1


In [4]:
for i,x in enumerate(['A','B','C']):
    print(i,2*x)

0 AA
1 BB
2 CC


In [5]:
for i in range(1,5):
    if (i!=2):
        print(i)

1
3
4


In [7]:
A.append([5,6,7])

In [8]:
A

[1, 2, 3, [5, 6, 7]]

In [9]:
B = [1,2,3,4,5,6,7]

In [10]:
B[:3]

[1, 2, 3]

In [11]:
B[3:]

[4, 5, 6, 7]

In [6]:
df = pd.DataFrame({'num_legs': [2, 4], 'num_wings': [2, 0]}, index=['falcon', 'dog'])

In [7]:
df

num_legs  num_wings
falcon         2          2
dog            4          0

1. To select rows whose column value equals a scalar, some_value, use **==**
2. To select rows whose column value is in an iterable, some_values, use **isin(values)** Whether each element in the DataFrame is contained in values.
3. Combine multiple conditions with &:

In [ ]:
df.isin

In [1]:
import numpy as np
m = np.array([2,4,6])
n = np.array([2, True, False])
print(m+n)

[4 5 6]


In [2]:
4+ True

5

In [3]:
m = np.array([2,6,4])
n = 2
print(m*2)

[ 4 12  8]


In [4]:
p = None
type(p)

NoneType

In [5]:
z = np.array([[5,9,8], [9,0,6]])

In [6]:
print(z[0:,1:])

[[9 8]
 [0 6]]


In [10]:
costs = np.column_stack(([2,1,2,1],[4,6,5,5]))
mean_costs = np.mean(costs[:,1])

In [11]:
print(costs)
print(mean_costs)

[[2 4]
 [1 6]
 [2 5]
 [1 5]]
5.0


In [13]:
f = lambda x, y : x * y

In [1]:
['a', 'b', 'c'] + [1, 2, 3]


['a', 'b', 'c', 1, 2, 3]

In [2]:
type(lambda x: x+1)

function

In [3]:
import numpy as np

In [18]:
r = [
    [0,1,2,3,4,5],
    [0,11,2,3,4,5],
    [0,1,22,3,4,5],
    [0,1,2,33,4,5],
    [0,1,2,3,44,5],
    [0,1,2,3,4,55]  
]

In [25]:
r = np.array(r)

In [26]:
r[:,::7]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [27]:
r.reshape(36)[::7]

array([ 0, 11, 22, 33, 44, 55])

In [28]:
r[0:6,::-7]

array([[ 5],
       [ 5],
       [ 5],
       [ 5],
       [ 5],
       [55]])

In [29]:
r[::7]

array([[0, 1, 2, 3, 4, 5]])

In [30]:
r[[2,3],[2,3]]

array([22, 33])

In [31]:
r[2:4,2:4]

array([[22,  3],
       [ 2, 33]])

In [32]:
r[::2,::2]

array([[ 0,  2,  4],
       [ 0, 22,  4],
       [ 0,  2, 44]])

In [33]:
r[2::2,2::2]

array([[22,  4],
       [ 2, 44]])

In [34]:
r[[2,3],[2,3]]

array([22, 33])

In [35]:
r[2:4,2:4]

array([[22,  3],
       [ 2, 33]])